name: Deploy

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-20.04
    environment: prod

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
 
      - name: Create dokku app if doesn't already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app
          ssh dokku@$DOKKU_HOST -C "dokku apps:create ${{ secrets.DOKKU_APP_NAME }}" | true
          echo The url is set by $HOSTNAME in secrets
          ssh dokku@$DOKKU_HOST -C "dokku git:initialize ${{ secrets.DOKKU_APP_NAME }}"
          ssh dokku@$DOKKU_HOST -C "dokku ps:set-restart-policy app unless-stopped"
          ssh dokku@$DOKKU_HOST -C "dokku ps:rebuild ${{ secrets.DOKKU_APP_NAME }}"

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: ${{ secrets.DOKKU_APP_NAME }}
            git-push-flags: --force

      - id: smoke-test
        name: Smoke test
        run: |
          set -x
          curl -v http://example.com
